# Generated by Django 2.2.3 on 2019-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNKNOWN', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10000)),
                ('supply', models.IntegerField(default=0)),
            ],
        ),
    ]
