# Generated by Django 2.2.3 on 2019-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ersb',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='game',
            name='supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='used',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='region',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
    ]
